# build stage
FROM node:18-bullseye as builder
WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# production stage
FROM node:18-bullseye-slim
WORKDIR /app

# copy only runtime artifacts
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
# copie node_modules apenas se necessário em runtime (ex.: libs nativas)
COPY --from=builder /app/node_modules ./node_modules

ENV NODE_ENV=production
ENV PORT=3000

EXPOSE 3000
CMD ["npm", "run", "start"]