jwt.keys.path=./keys

jwt.private.key=file:${jwt.keys.path}/private.pem
jwt.public.key=file:${jwt.keys.path}/public.pem

cloudflare.r2.access-key=ad73ee447e7090b774d9aedba3128b75
cloudflare.r2.secret-key=2b2ff6c61963f4ffed143935df019e20d3c8898b93152d34043f109640e41067
cloudflare.r2.endpoint=https://5b1082ca8d9def07cf0a0cb57b422d2f.r2.cloudflarestorage.com
cloudflare.r2.bucket=crm-base-storage

spring.application.name=crm-base



#EM AMBIENTE DE PRODUÇÃO A LINHA ABAIXO DEVERÁ SER COMENTADA
server.error.include-message=always
server.error.include-stacktrace=always
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

#CONFIGURAÇÕES DE CONEXÃO COM O BANCO DE DADOS
spring.datasource.url=jdbc:postgresql://${DB_HOST_DEV}/${DB_NAME_DEV}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME_DEV}
spring.datasource.password=${DB_PASSWORD_DEV}


#HIBERNATE DDL AUTO (create, create-drop, validate, update)
spring.jpa.hibernate.ddl-auto=update

#CONFIGURAÇÃO QUE DEFINE A FORMA COMO O MAPEAMENTO DO JPA IRÁ TRABALHAR
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#LOGANDO/PRINT DOS COMANDOS SQL GERADOS PELO SPRING DATA
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true

# #CONFIGURAÇÃO DO SWAGGER
# spring.mvc.pathmatch.matching-strategy=ant_path_matcher

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
